### ISSUE TITLE
Hi, how can I hide chests or rares when I need to?

### ISSUE THREAD

**Issue by hbltth** [Lexiebean/AutoDB#2]
Thanks for your work, can I hide chests or rares with this addon? I have some problem with AutoDB2.

**Comment by Lexiebean** [comment]
You should be able to shift+click on the type of pin that you want to hide, or whatever the pfquest functionality was. 

Or you can edit the code yourself. It's pretty basic.

* Open up AutoDB.lua with notepad or any other text editor. 
* Add a `--` at the start of the line that contains the type of mark you don't want to see. 
* Save the file (Ctrl+S)
* Reload your UI in-game (`/rl`)

Then remove the `--` again, save and reload again any time you'd like to see them again.

**Comment by hbltth** [comment]
> You should be able to shift+click on the type of pin that you want to hide, or whatever the pfquest functionality was.
> 
> Or you can edit the code yourself. It's pretty basic.
> 
> * Open up AutoDB.lua with notepad or any other text editor.
> * Add a `--` at the start of the line that contains the type of mark you don't want to see.
> * Save the file (Ctrl+S)
> * Reload your UI in-game (`/rl`)
> 
> Then remove the `--` again, save and reload again any time you'd like to see them again.

Thanks for your reply.
